#!/bin/bash

function main {
    local file="$1"
    local pitch="$2"
    local gain="$3"
    [ -z $pitch ] && pitch=1.0
    [ -z $gain ] && gain=1.0
    ./lightning-client play "$file" $pitch $gain
}

main "$@"
